# The chance a glass bottle breaks when the item in the offhand evaporates the water, giving back an empty (air) bottle.
chanceGlassBottleBreaksWithFireTypeInOffhand: 0.5

# The amount of air an empty bottle contains. In vanilla Minecraft, 300 is the maximum air supply.
amountOfAirInBottles: 150

# chanceGlassBottleBreaksWithFireTypeInOffhand: default = 0.5, min 0, max 1.0
# amountOfAirInBottles: default = 150, min 0, max 300